-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Versi server:                 10.1.32-MariaDB - mariadb.org binary distribution
-- OS Server:                    Win32
-- HeidiSQL Versi:               9.5.0.5196
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Membuang struktur basisdata untuk laravel_crud
CREATE DATABASE IF NOT EXISTS `laravel_crud` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `laravel_crud`;

-- membuang struktur untuk table laravel_crud.migrations
CREATE TABLE IF NOT EXISTS `migrations` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `migration` varchar(191) COLLATE utf8_unicode_ci NOT NULL,
  `batch` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- Membuang data untuk tabel laravel_crud.migrations: ~2 rows (lebih kurang)
/*!40000 ALTER TABLE `migrations` DISABLE KEYS */;
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES
	(1, '2014_10_12_000000_create_users_table', 1),
	(2, '2014_10_12_100000_create_password_resets_table', 1),
	(3, '2018_07_12_224852_create_posts_table', 1);
/*!40000 ALTER TABLE `migrations` ENABLE KEYS */;

-- membuang struktur untuk table laravel_crud.password_resets
CREATE TABLE IF NOT EXISTS `password_resets` (
  `email` varchar(191) COLLATE utf8_unicode_ci NOT NULL,
  `token` varchar(191) COLLATE utf8_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  KEY `password_resets_email_index` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- Membuang data untuk tabel laravel_crud.password_resets: ~0 rows (lebih kurang)
/*!40000 ALTER TABLE `password_resets` DISABLE KEYS */;
/*!40000 ALTER TABLE `password_resets` ENABLE KEYS */;

-- membuang struktur untuk table laravel_crud.posts
CREATE TABLE IF NOT EXISTS `posts` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(191) COLLATE utf8_unicode_ci NOT NULL,
  `body` text COLLATE utf8_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- Membuang data untuk tabel laravel_crud.posts: ~18 rows (lebih kurang)
/*!40000 ALTER TABLE `posts` DISABLE KEYS */;
INSERT INTO `posts` (`id`, `title`, `body`, `created_at`, `updated_at`) VALUES
	(3, 'Repellat et dolore culpa sit ratione ratione aut distinctio laborum est sed.', 'Odit ad quis officia quod non voluptas. Natus quam quis voluptates et eaque modi voluptas voluptas. Ut itaque quis eos commodi id. Sit odio et nulla. Et ratione eligendi iusto qui dolorem est. Eveniet rerum reiciendis vero ut voluptas quo. Quia alias ut facilis deserunt delectus. Voluptas odio repudiandae harum. Reiciendis est reiciendis in vitae laudantium dolorem saepe nesciunt. Ipsa nihil a eum sequi cum. A ab corporis itaque nostrum sequi libero quo. Nihil voluptas odio sunt dolor autem ducimus sed. Delectus vero eius aliquid quae accusamus sed. At aliquid nostrum ipsam omnis sit ipsum. Quisquam cupiditate nostrum nihil commodi libero. Laboriosam quia qui iure necessitatibus occaecati laboriosam. Deleniti itaque est distinctio vero voluptatem facilis. Ducimus est est rerum eaque aut. Tempore excepturi sed corporis et et odit animi. Eaque vel velit qui quia ullam. Voluptatum earum labore non accusamus mollitia animi quia consequatur. Quo porro facere et aut non. Laudantium enim minus unde. Accusantium laborum enim vero. Incidunt tenetur saepe quas ut. Voluptatibus sint eum suscipit autem. Ipsum quia harum voluptatem odio consequuntur corporis dolor quia. Distinctio dolore ullam rerum. Eligendi et nulla unde est quaerat fugit sint. Totam saepe dolorum reiciendis porro atque rerum. Velit suscipit autem velit dolore iste repellendus. Dolorum ut quae esse exercitationem quis at repudiandae. Voluptatibus expedita perspiciatis culpa dignissimos tempore ut in laborum. Neque voluptatum quam facilis non id architecto consequatur.', '2018-07-12 23:47:08', '2018-07-12 23:47:08'),
	(4, 'Pariatur perspiciatis architecto consequuntur doloremque esse fugit dicta perferendis ut voluptatum sequi.', 'Eaque illo nam sequi. Fuga qui dolor non eaque. Aut et vitae dolore praesentium molestias. Voluptatibus laudantium et quod. Architecto qui excepturi tempora eos voluptatum suscipit. Dolores consectetur qui dolorem voluptatibus illum omnis. Iure minima nam optio illum numquam veritatis. Officiis corporis alias sint et. Rem laborum et reprehenderit velit. Ipsa illo et qui maiores. Tenetur consequuntur est fuga ut aut. Ab et aut harum maxime ex voluptas. Reiciendis aut tempore voluptatem molestiae quaerat. Autem et nesciunt aut quidem esse rerum eum. Ullam architecto ipsum error non. Error dolor sit distinctio commodi aut maiores laboriosam. Excepturi dolores harum qui et perspiciatis sequi eos. Similique omnis dicta officiis laborum sunt maiores. Et dolores qui omnis voluptatum blanditiis. Nostrum nihil veniam nam ipsa. Et quisquam enim excepturi id. Expedita impedit nemo quibusdam enim expedita pariatur. Unde facilis ut autem debitis est quos. Consectetur qui quis asperiores. In voluptas vero sit velit dolor velit ratione porro. Omnis facere est in sunt et nesciunt dolores. Illum voluptatem atque eos suscipit impedit. Esse esse impedit sit alias. Officia a porro quos a a consequatur quos et. Nihil et quis est.', '2018-07-12 23:47:08', '2018-07-12 23:47:08'),
	(5, 'Iusto et nemo ea dolorem nisi voluptatem.', 'Tenetur aliquid ipsam quas neque soluta quo. Quod minus perspiciatis labore in ut sunt delectus. Exercitationem vel et ipsum dignissimos quia. Corporis non architecto id. Dolore sed eum delectus neque est temporibus qui maiores. Nam qui qui vel voluptatibus. Ducimus quibusdam labore quo vel impedit minus. Quasi ipsam suscipit aut accusamus laboriosam et qui. Sit a reprehenderit dolore quos. Molestias quae doloremque incidunt quas possimus magnam aut. Quo officiis voluptatibus officia aut magni fugit quas. In optio eos enim nostrum praesentium non unde. Possimus beatae et quidem minima aut ut id quia. Omnis voluptatem asperiores repellat adipisci. Qui voluptatibus aliquam accusantium suscipit. Id dolor beatae doloribus sint occaecati. Quaerat sunt nulla aut excepturi. Qui ab cum aspernatur perspiciatis illum. Ut eos enim et aut. Repellat delectus suscipit hic asperiores sit voluptates. Delectus error minima excepturi ducimus repudiandae doloribus aliquid eos. Aspernatur accusamus fuga eaque suscipit. Necessitatibus vel totam illo et delectus. Quaerat modi maxime aliquam autem nesciunt molestiae. Fuga qui magnam perspiciatis modi voluptatibus est tenetur officiis. Neque pariatur facilis atque quos dolor reiciendis possimus. Iure non tenetur eos magnam doloribus. Non qui nihil et numquam voluptatem quo suscipit. Quas magni ut quis iure sit distinctio. Quaerat delectus consequatur nobis quas error animi. Est dolores quibusdam alias amet explicabo eum necessitatibus. Eveniet ratione laboriosam neque ut ipsum soluta saepe. Natus incidunt adipisci numquam in. Sed atque qui perspiciatis inventore beatae consequatur molestiae eaque. Ea neque qui assumenda et omnis. Libero qui quia ut facere accusantium. Vero quam consequuntur asperiores culpa qui.', '2018-07-12 23:47:08', '2018-07-12 23:47:08'),
	(6, 'Quis minima cum quia consequatur distinctio nihil voluptas ut sunt autem accusamus eveniet.', 'Tempore provident qui sed nulla repellat harum. Id ab iure veniam quis. Iure alias officiis omnis. Cum unde est aut quia asperiores. Laborum harum dolorem facere aut molestias cumque et. Iste expedita et eveniet repellat perferendis eligendi ipsam. Illo voluptatem suscipit saepe reiciendis qui quibusdam aperiam. Praesentium quaerat suscipit et ut sit qui sint. Eum delectus deleniti rerum qui a assumenda. Odit cumque debitis consequuntur odio repudiandae. Ratione vitae necessitatibus fugiat dolorem exercitationem dolorem. Et enim perspiciatis rerum repellat. Ab tempora fugiat et et aut ducimus voluptatem. Aspernatur voluptatem fugiat corporis facere. Eveniet sunt saepe itaque. Et iusto cum consequatur harum doloribus dolorem. Non pariatur earum at rem est atque quas. Est et minus laboriosam illum laborum qui. Et aut impedit voluptatum aut ut. Velit error unde voluptas exercitationem. Eveniet inventore et laudantium. Est dolores rem est inventore explicabo. Atque ea omnis aliquid ab optio. Voluptatibus quia expedita cum atque. Saepe aut optio repudiandae amet eos. Vel rem pariatur saepe laudantium nam rem. Et neque dolorem ipsum voluptatibus.', '2018-07-12 23:47:08', '2018-07-12 23:47:08'),
	(7, 'Rerum laudantium adipisci voluptatem eos quisquam voluptatum totam.', 'Labore occaecati fuga impedit. Enim asperiores autem exercitationem id est mollitia quo. Sed ut eum id autem iusto consectetur. Debitis odit soluta fuga sed aspernatur accusantium. Modi dolorem est sit omnis nisi fugiat explicabo. Et quas ratione tempora ab sit. Facilis ut eaque ex ducimus earum quasi optio harum. Eum pariatur quidem earum velit dolorem. Possimus ipsam eveniet aliquam rerum. Dolore quia accusamus blanditiis consequuntur. Veniam accusamus assumenda totam sunt ad ea accusamus. Illum est sint cumque omnis totam magni blanditiis. Veniam optio quia ut tempora sunt optio. Quis cupiditate voluptate consequatur vero magnam. Ea voluptates totam in voluptatem commodi enim voluptas. Repudiandae porro doloribus voluptatem occaecati dolorem. Recusandae harum earum quod deleniti sed. Ipsam ratione cumque sit aut quo voluptas. Et inventore eligendi quo qui alias. At omnis molestias aut est minima repellendus. Eaque commodi voluptatem non iure asperiores aspernatur suscipit. Blanditiis sint eligendi facere neque sed accusamus architecto. Suscipit numquam error libero sed dolorum molestiae. At beatae est eligendi quibusdam. Veritatis et molestiae omnis ut possimus. Eveniet maxime magnam autem vel ratione. Tenetur mollitia neque praesentium provident. Aut quis ea laudantium sed corrupti et. Laudantium ex sit molestiae libero sed repellendus. Deleniti ut ipsum tempora sunt id et. Molestias tenetur omnis voluptas tempore. Blanditiis velit explicabo atque esse. Molestiae tempora odit blanditiis beatae laborum consequuntur aspernatur sunt. Animi ut incidunt ducimus. Excepturi animi eum excepturi sit. Deleniti modi et aperiam. Minima nisi et temporibus sit distinctio blanditiis. Laudantium quibusdam non omnis id aut et sit praesentium. Nobis eum hic sunt aut delectus unde. Repellendus aut dolorum sed et quam fuga enim sint. Autem enim nam repellendus at non dolor est.', '2018-07-12 23:47:08', '2018-07-12 23:47:08'),
	(8, 'Suscipit provident qui sit dolorum ad aliquam voluptatem quasi omnis eligendi dolor possimus.', 'Nihil adipisci nulla in asperiores quae quo cumque. Autem tenetur eos et dolorem nulla nobis ut. Tempore architecto et quia nisi illum sit. Iusto sint dolores consequatur ipsam autem ea. Doloribus possimus culpa inventore repellat dolor error ea. Voluptatem itaque unde enim ut earum sed culpa eligendi. Nihil vitae nulla temporibus quia temporibus qui dolor. Placeat et et non numquam. Eum ab dolor tempore quidem labore vero eius. Est voluptatibus vel ut hic fuga. Eaque nam sed esse voluptatem neque. Consectetur quo beatae laborum suscipit amet quia quia sit. Iste qui ipsa ut odit nihil earum. Est ducimus sed repellendus ipsum. Fugit et quod quia ea aut ut voluptatem. In rerum nihil est impedit maxime numquam non fugiat. Quia atque eum magnam aspernatur aut. Ut autem ipsa alias modi sit magni suscipit voluptatum. Delectus sed autem voluptatem consequatur iure. Distinctio at consectetur iusto et et. Illum et repellat et omnis quia. Quas natus tenetur numquam dolorem nihil. At doloribus voluptates autem corrupti iure. Et tenetur quidem et. Commodi sed quidem similique doloremque aut dicta nostrum. Minima aut et qui delectus.', '2018-07-12 23:47:08', '2018-07-12 23:47:08'),
	(9, 'Omnis deleniti labore est ad illo assumenda itaque quia earum qui.', 'Id id autem accusamus. Iure repudiandae molestiae autem minima perferendis excepturi. Quis incidunt deserunt repellat dignissimos. In nihil quis reiciendis. Repellendus quas rem accusantium labore. Et provident quis tenetur enim quis. Neque ullam rerum autem ad suscipit hic voluptas. Ad assumenda ea eveniet. Voluptas recusandae exercitationem neque consequatur aspernatur. Dicta perspiciatis saepe accusamus sequi est laboriosam. Et voluptas et voluptate delectus. Repellat alias illum et non sit rerum debitis. Distinctio exercitationem minima asperiores non eos autem aliquid. Et sint quisquam nostrum repudiandae odit nihil. Distinctio excepturi possimus amet facilis iste debitis temporibus. Ipsa praesentium ut ipsum fugiat incidunt. Sit sit exercitationem quos. Et id fuga autem velit ut a consectetur. Et cumque doloribus nulla in eos dolores. Sed voluptas vitae sit similique iure id non. Voluptatum illo dignissimos repellat et. Consequatur officiis quibusdam tenetur vitae voluptates aut.', '2018-07-12 23:47:08', '2018-07-12 23:47:08'),
	(10, 'Nemo quia ab vitae non consequatur et error similique ut molestias enim.', 'Autem autem quo fugit est. Quis error et a ea. Quia quibusdam nisi in maxime qui assumenda. Eum aliquam animi iste aliquam id quo. Incidunt porro velit delectus laboriosam voluptatum nisi voluptates. Asperiores quo doloribus et nihil enim perferendis. Iusto commodi nisi hic enim. Voluptates veniam similique consequuntur dolores enim perferendis accusantium et. Praesentium quia error maxime in adipisci ab. Nesciunt quia iure itaque. Saepe rerum est dicta ipsa qui. Voluptatem asperiores maiores harum placeat. Adipisci neque voluptate nulla aut dolorum. Quia in est praesentium ad ipsum culpa perferendis. Facere quisquam consectetur at et excepturi. Eius ullam dicta quidem saepe minima totam. Inventore vitae accusamus aspernatur repellat quos molestiae. Dolore quis libero animi excepturi omnis vero perspiciatis. Architecto delectus distinctio hic ea ea esse necessitatibus. Numquam dolorem aut nulla corporis et. Earum in qui neque dolor et exercitationem. Sequi architecto ad nihil excepturi eos. Quam voluptate voluptatem maxime amet qui autem est impedit. Eum animi id officiis nobis vero dolor fugit molestias. Harum molestiae aperiam et et delectus quas. Quidem illo odit a libero et quia autem. Nihil amet doloremque quis sit. Facere et aut quae doloremque dolorum consequatur. Sapiente reiciendis molestias aperiam sit iure.', '2018-07-12 23:47:08', '2018-07-12 23:47:08'),
	(11, 'Nobis quas itaque est animi esse cupiditate cumque doloribus.', 'Eos expedita et illum iusto provident. Eos libero eius perferendis neque error. Voluptatibus nisi qui voluptas voluptatem ipsam qui. Quod facilis qui repudiandae aperiam eos. Ducimus architecto sint fugit ut. Et molestias vel cum id cupiditate iusto nam. Doloremque magni cumque non necessitatibus aperiam quibusdam sit. Et veniam voluptatem necessitatibus alias dolore. Laborum ratione id corrupti eos aut. Ipsam minima voluptas quis quia eos et. Corrupti sed mollitia eligendi sequi doloribus. Dolorem enim distinctio sit aut. Non debitis aut et quia fuga nihil ut. Eius adipisci voluptates sunt quia corrupti et necessitatibus. Blanditiis accusantium repudiandae tenetur ut ducimus consequuntur ut. Dolorem praesentium explicabo non recusandae porro ipsa. Minus nulla ea minima aliquid similique. Commodi quidem et quibusdam omnis beatae fugit quod. Occaecati qui commodi sed natus. Consequatur necessitatibus molestiae ratione. Officiis voluptatem aspernatur eum sunt sequi. Nisi enim dolor optio cum.', '2018-07-12 23:47:08', '2018-07-12 23:47:08'),
	(12, 'Dolor voluptatum voluptatem ad quia et saepe aut mollitia ducimus distinctio.', 'Est molestiae iste quidem dolorum rerum voluptas. Alias doloremque recusandae officiis laborum non laudantium et. Quisquam ea omnis a doloremque. Molestiae aliquid fuga ea et laborum enim nostrum. Eveniet accusantium quibusdam tempore adipisci. Beatae at consequuntur ab autem. Ut enim dolorem natus rerum est quam cumque atque. Alias ut quia dolore laboriosam ullam quasi. Ullam aut quia corrupti odio aut ut earum. Laboriosam eum ipsam qui beatae dicta. Vel voluptatibus et delectus nobis cupiditate rem. Sit fugiat quas reprehenderit natus non quia eum. Nesciunt quam nihil accusamus et et. Quos ad quia ullam. Voluptatum fugit voluptatum ut nihil saepe. Aperiam possimus nesciunt ea perspiciatis non omnis qui. Qui ut vitae qui facere. Quidem quo aliquam est qui iure sit dolores itaque. Illum quo adipisci rerum perspiciatis a. Adipisci voluptatem aliquam ut dignissimos ipsam et suscipit soluta. Dicta dolores et ullam provident rerum eius et. Nihil rerum corrupti qui corrupti non blanditiis occaecati quia. Dicta eos iure possimus aut dicta. Placeat alias velit repellat sit neque. Aut odit odio enim illum. Quia nemo eum unde. Quisquam rerum tenetur nihil. Nihil molestiae laboriosam asperiores porro sint. Ut ratione praesentium reiciendis tenetur quibusdam doloribus laboriosam.', '2018-07-12 23:47:08', '2018-07-12 23:47:08'),
	(13, 'Est rerum eaque quia ab omnis occaecati et necessitatibus voluptatem ut illo voluptatem.', 'Sit dolorum suscipit assumenda sint non odio autem. Rerum perferendis ullam aliquid dolor architecto repudiandae. Quia aut optio est. Sunt non aut doloremque commodi. Necessitatibus deleniti sint culpa voluptatem eveniet sapiente. Occaecati et voluptatibus ab ut veritatis sunt id. Temporibus expedita et et ut. Tempore et est ad animi. Eum dolor eos enim dolorem quam iure vero aut. Esse non ad accusamus et officiis. Et id necessitatibus accusantium pariatur sed earum qui. Quod fuga et inventore. Commodi reiciendis tempora et officia repudiandae est eius. Et qui fugiat deleniti ratione. Ipsum voluptatem est autem alias autem. Sed ut consequatur id voluptatem dolorum. Reprehenderit recusandae quae eos est. Voluptatum maiores qui sapiente laborum soluta veritatis similique adipisci. Nisi est amet sint ab dolorem. Illum explicabo consequatur quis ad expedita. Consequatur doloribus sit est similique. Rerum ducimus est porro dolor enim. Veritatis ut iusto laboriosam autem quidem dolores provident. Neque quis adipisci et dolor. Sunt nesciunt velit dolorem rem enim perspiciatis expedita rerum. Ut aut voluptatem recusandae reprehenderit optio aliquam sapiente. Voluptatum autem dolor nisi eos dolorem. Voluptates rerum suscipit iusto veritatis ut quia. Rerum quia est quo occaecati omnis. Fugit explicabo adipisci id quo. Pariatur iusto est ut voluptatum qui.', '2018-07-12 23:47:08', '2018-07-12 23:47:08'),
	(14, 'Et aut numquam at voluptas qui et corrupti inventore rem et sunt officiis commodi.', 'Et sit suscipit odit. Dolor corporis quo voluptate. Placeat quis magnam quos et eos et in. Sunt provident qui pariatur autem. Numquam esse sed id ipsam. Nemo labore molestias quos aut non. Nesciunt et porro dicta est. Voluptatum porro ea eos velit iure autem quod. Id voluptatem a fuga inventore reprehenderit est veritatis. Nihil est libero dignissimos quos ut deserunt. Quisquam vel molestiae nihil odio eos. Dolor perferendis id id nostrum. Quam est ut ea numquam excepturi et. Quae et quo modi iste. Magnam eum et quidem consequatur. Consequatur dolores qui commodi dolores commodi necessitatibus. Recusandae ut ab voluptates officia. Dolore totam eos mollitia soluta eaque sit voluptas. Voluptas occaecati soluta totam accusantium totam. Nam mollitia velit voluptas voluptatem et tenetur et. Cupiditate voluptates necessitatibus in quis. Itaque cupiditate est ut ut tenetur vero suscipit. Magni quia iure provident quod. Voluptatem et aliquam eum sint odio culpa occaecati. Est excepturi corrupti voluptate excepturi vero veniam ut ut. Illum voluptatem eum voluptas. Inventore alias id maiores nisi. Neque aut sint amet occaecati doloremque aut.', '2018-07-12 23:47:08', '2018-07-12 23:47:08'),
	(15, 'Et ad doloribus temporibus officia eum eos qui quidem non quia laudantium et eligendi.', 'Dolor eligendi impedit et nemo voluptate facere. Rerum libero labore et ut architecto quibusdam. Dolorem voluptatibus reprehenderit omnis dolor. Nisi velit et voluptates qui consectetur eius. Nesciunt sequi veniam consequatur eum et et ab. Quia ut quasi quo cupiditate et occaecati sit dolorem. Ipsa iusto labore aliquam. Consectetur maiores corporis ut fugiat. Ut fuga assumenda veritatis sit deserunt error modi enim. Nostrum dolore et debitis porro labore nemo. Pariatur ipsum quod ut quam. Est atque distinctio officiis qui aspernatur sequi magni voluptatem. Autem non vel et aut consequatur culpa libero. Voluptatibus pariatur dolores doloribus repellendus velit ut accusantium. Quisquam reprehenderit at mollitia perspiciatis. Ut sed asperiores culpa dolores minima culpa. Voluptate repudiandae et ut est consequatur et labore. Minima enim exercitationem blanditiis beatae rerum ipsa. Beatae animi sit mollitia suscipit quaerat repudiandae. Qui laudantium omnis aut aut nihil. Veritatis culpa sunt ducimus. Aut minima dolorum error et aut. Officiis qui eum nemo voluptatibus autem nostrum aut assumenda. Nulla cupiditate hic explicabo suscipit iure esse. Necessitatibus corporis quisquam voluptatem aliquam aspernatur ab. Hic optio dicta culpa eius. Fugit eius assumenda aut illo sit et. Omnis ea quis consequatur ducimus explicabo veniam molestiae. Quod deleniti occaecati est placeat. Qui ut ab laudantium nam reprehenderit est aut sapiente. Deserunt accusantium ipsum reprehenderit rem natus modi eaque. Perferendis odio ut sunt veniam error. Alias est totam et vitae vel. Tempore laborum facere et tempora officiis voluptatum ut esse.', '2018-07-12 23:47:08', '2018-07-12 23:47:08'),
	(16, 'Est facilis dolore non laudantium molestias error minus et dolore.', 'Nulla accusamus molestiae repellat qui doloremque. Quod asperiores atque placeat quia sed ex numquam quia. Voluptas totam natus quos ratione voluptatem qui. Ut dolores eum reiciendis amet cupiditate ad. Molestias quia voluptatem impedit beatae corporis. Exercitationem doloribus qui assumenda repudiandae non odio quasi. Porro iure est qui saepe asperiores in. In error quas ullam inventore. Repudiandae et quis accusamus commodi possimus nam. Ut commodi et cum commodi nihil eaque nihil. Unde iure possimus maiores ea facere deleniti rerum. Sunt quis quos inventore aspernatur sapiente nobis. Placeat suscipit culpa magnam officiis quia quis. Veniam nostrum libero ut repellendus quaerat itaque animi. Qui deserunt sapiente incidunt dolorum autem. Corporis fugiat dolorem sint dolores. Animi rerum molestias et est et et. Recusandae ut maxime qui rerum. Aut minus nam odit enim dolorum molestiae totam odio. Dolore repellendus assumenda optio placeat doloribus. Quia fugiat ipsum magni non nisi optio tenetur odio. Pariatur odit eos quae dignissimos placeat et tempora. Repellendus beatae laborum molestiae nesciunt fugit eos. Qui reiciendis est libero quisquam ut error. Rerum consequuntur et rerum magnam iusto non necessitatibus. Quam laudantium fugit autem magnam. At assumenda perferendis officiis veniam. Animi sed accusamus nam fuga enim modi sit eligendi. Blanditiis enim blanditiis sit id. Et id voluptas assumenda sunt ex quasi. Aut molestiae aspernatur sapiente autem aut non. Cumque est esse culpa earum cupiditate. Eligendi recusandae et neque ut corrupti et molestias. Architecto sint et illo itaque delectus quia quos. Ipsum sed modi ex quia nulla sapiente. Dolor quasi dolorem dolorem. Aliquid ea veritatis recusandae omnis beatae.', '2018-07-12 23:47:09', '2018-07-12 23:47:09'),
	(17, 'Molestiae accusamus odio sed quos consequatur fugiat inventore sint impedit laboriosam quo dolorem.', 'Dolores expedita et enim voluptatibus error omnis provident est. Odio dolore excepturi soluta illo iure sapiente voluptatem. Placeat at vel suscipit soluta fugiat at. Mollitia iure cupiditate natus sint est enim aut explicabo. Nihil aliquid esse laudantium nam. Iure recusandae porro ut doloremque. Eos minima ratione ex sunt amet adipisci est similique. Aspernatur modi eius animi est. Tempora nam occaecati laboriosam. Nisi facilis id tempore sit. Repellat quibusdam voluptatem maxime ratione itaque repellendus. Iusto voluptatum corporis et eius voluptatem veritatis. Cupiditate in et modi neque vel. Nulla beatae iusto architecto et odio. Voluptatem ipsam quasi nihil. Eaque dolore impedit alias neque magni minima ea. Qui aliquid eum sed et odit est commodi sapiente. Enim necessitatibus in excepturi quidem iure. Doloribus non fuga velit voluptate. Nihil dicta id amet perspiciatis maxime. Voluptas quidem delectus aut reiciendis voluptas laudantium reprehenderit. Quia et facilis sapiente at et. Veritatis dolore optio et corrupti. Veritatis debitis fugit praesentium. Dolorem id similique accusamus placeat doloremque. Saepe reiciendis dolore laboriosam molestiae enim dolorem culpa voluptates. Perspiciatis nemo quibusdam quia aspernatur libero quos. Inventore cum voluptas tenetur ex repudiandae officiis. Est et eum nemo aut. Sunt nostrum voluptatibus quis aliquid non. Consequuntur rerum magnam delectus eligendi tempora rerum saepe. Voluptas debitis enim pariatur. Consequatur enim illum ab nemo vero laboriosam placeat. Dolorum voluptas ducimus tenetur totam ut inventore voluptatem atque. Odit ipsa necessitatibus voluptatem beatae doloremque aliquid. Distinctio nesciunt qui placeat est corporis alias exercitationem. Facere sapiente voluptas delectus quidem sit. Et qui est et qui qui error sapiente.', '2018-07-12 23:47:09', '2018-07-12 23:47:09'),
	(18, 'Et autem adipisci quam sit odit sit modi est et commodi soluta.', 'Corporis earum fugit nobis nostrum. Reprehenderit dolores occaecati aliquam sed omnis laudantium unde. Tenetur laudantium quia iure nam explicabo. Doloremque tenetur harum corrupti sed hic possimus. Vero nemo facere voluptatum voluptas eum voluptatem. In illum aperiam soluta. Voluptate velit in quos. Eum sit quo exercitationem neque delectus sapiente. Fugiat qui saepe non quod et alias provident eligendi. Possimus quaerat corrupti nemo quo. At et excepturi reiciendis ut dolor deserunt. Quibusdam autem aut illo odit sint et et. Beatae alias non voluptas voluptate fuga. Reiciendis corporis assumenda illo sit eveniet tempora. Enim omnis unde qui quaerat tenetur quo. Voluptates voluptatem illo optio optio sint quas doloremque. Quo beatae nesciunt ab. Consectetur dignissimos debitis sequi similique. Distinctio totam vero aperiam ratione repellat. Quo sunt vel praesentium voluptatem ullam. Ipsa ipsam dolorem non eum. Expedita optio velit voluptatem eius rerum expedita. Ipsa voluptatem laborum in occaecati possimus odio. Nihil illo enim tenetur suscipit est sit. Facilis recusandae nihil temporibus architecto corrupti praesentium commodi. Quia dolores cupiditate dolorem voluptatem. Voluptatem reiciendis omnis consequatur sequi. Molestiae repudiandae id molestias qui. Iure odit temporibus quibusdam enim numquam. Natus ea qui maxime accusantium facere delectus odit. Explicabo sit rerum qui fugit quaerat delectus aut. Facilis possimus reiciendis quia quis esse. Nostrum nemo earum quia quas harum id molestiae. Sequi alias occaecati autem accusamus architecto alias aut autem. Qui consequuntur sit consectetur et repellendus et commodi id. Tempora iure error in est dolore temporibus aut.', '2018-07-12 23:47:09', '2018-07-12 23:47:09'),
	(19, 'Corporis in iure impedit modi quia dicta.', 'Ut reiciendis architecto et. Et dolores perspiciatis adipisci omnis. Placeat dolorum aperiam iure esse sapiente quos eum sunt. Omnis deserunt ducimus quod in. Qui aperiam necessitatibus nihil quidem excepturi dolor. Nihil temporibus omnis rem magni nobis provident sapiente. Et quas et adipisci. Ut iusto est aut praesentium quisquam. Voluptate quae consectetur aut. Et repellendus labore aspernatur rerum consequatur quidem. Facere ex in id natus. Et minima placeat dolor tempora. Culpa et dolor in ut. Repellat iure odit aspernatur maiores et molestias. Quis voluptatem omnis consequatur perferendis asperiores ipsam. Architecto vel error repellendus quia excepturi quo optio libero. Et sit nulla natus voluptatibus. Quidem aperiam labore excepturi facere quo. Sed aut est omnis fugiat voluptatibus. Repellat qui totam facilis aut rerum. Itaque laborum tenetur rem doloremque incidunt in tenetur nisi. Autem fugiat qui harum aspernatur et non dolor. Rerum voluptatem vitae aut omnis velit sint est. Adipisci facilis consequuntur consectetur cumque delectus.', '2018-07-12 23:47:09', '2018-07-12 23:47:09'),
	(20, 'Blanditiis deserunt in sed aliquid eligendi consequatur consequuntur amet dolores qui.', 'Rem et accusamus nihil quis rem magnam. Dignissimos ut magni velit tenetur neque reprehenderit. Atque est voluptatem dolores enim. Enim eius delectus quo reiciendis amet. Ea perferendis ipsum reiciendis commodi quo. Possimus ullam asperiores sit omnis. Esse porro rem et perspiciatis ut voluptate qui. Non accusantium libero earum et quibusdam. Harum consectetur ipsa et. Nobis ut architecto aut sunt beatae officiis. Ullam commodi nobis accusantium et quos molestias dolores. Laboriosam eos ipsum ab veritatis esse eveniet nemo est. Consectetur quam omnis inventore dolores dolorum inventore velit. Maxime corrupti quaerat consectetur asperiores quia explicabo et natus. Placeat consequatur tempora ea magni eaque. Temporibus voluptatum ratione iusto quia. Molestias sequi sed dicta et eveniet. Facilis facilis harum inventore nihil. Unde debitis aspernatur ab laborum voluptas. Voluptas ab eaque iste alias et et et. Error et dolore hic voluptas eveniet sequi. Minus vel soluta sint laborum. Necessitatibus et sint mollitia aliquid. Similique voluptates et doloremque voluptatem ratione quis iste. Quibusdam quasi quas quia quidem qui. Et eaque blanditiis harum odio facilis officia. Fuga ullam eius omnis. Est ad perferendis beatae voluptas dignissimos autem temporibus. Dolores nulla sequi in facilis consequatur. Eum laborum et commodi excepturi officia aut. Et autem eligendi vel eos ratione accusantium ea. Quasi quos inventore enim. Nostrum laborum accusantium sed qui. Soluta tenetur officia fugiat qui nemo quae qui. Iste asperiores rem eos culpa et.', '2018-07-12 23:47:09', '2018-07-12 23:47:09');
/*!40000 ALTER TABLE `posts` ENABLE KEYS */;

-- membuang struktur untuk table laravel_crud.users
CREATE TABLE IF NOT EXISTS `users` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(191) COLLATE utf8_unicode_ci NOT NULL,
  `email` varchar(250) COLLATE utf8_unicode_ci NOT NULL,
  `password` varchar(191) COLLATE utf8_unicode_ci NOT NULL,
  `remember_token` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_email_unique` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- Membuang data untuk tabel laravel_crud.users: ~0 rows (lebih kurang)
/*!40000 ALTER TABLE `users` DISABLE KEYS */;
/*!40000 ALTER TABLE `users` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
